trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: VercelDeploymentArquest

steps:
  - checkout: self

  - script: npm install -g pnpm
    displayName: "📦 Install pnpm"

  - script: pnpm install --frozen-lockfile
    displayName: "📥 Install dependencies"

  - script: npm install -g vercel
    displayName: "🛠 Install Vercel CLI"

  - script: |
      vercel --prod --force --token=$(VERCEL_PAT)
    env:
      VERCEL_PROJECT_ID: $(VERCEL_PROJECT_ID_ARQUEST)
      VERCEL_ORG_ID: $(VERCEL_ORG_ID)
    displayName: "🚀 Deploy to Vercel (ARQUEST)"
