import path from "path";
// next.config.mjs
import withPWA from "next-pwa";

/**
 * Whether we’re building for production.
 */
const isProd = process.env.NODE_ENV === "production";

/**
 * Wrap Next config with next-pwa.
 *
 * Notes:
 * - The service worker is generated by Workbox with the rules below.
 * - We add mild cache heuristics for APIs, JSON, static assets and common CDNs.
 * - The external-requests rule uses `globalThis.location.origin` instead of `self`
 *   to avoid references that can warn in non-SW contexts during build.
 */
const withPWAInit = withPWA({
  dest: "public",
  disable: !isProd,         // only enable PWA in production
  register: true,           // auto-register SW
  skipWaiting: true,        // update SW immediately
  cacheStartUrl: true,
  dynamicStartUrl: false,
  buildExcludes: [/middleware-manifest\.json$/],

  // Fallback page when offline (make sure /app/offline/page.tsx exists)
  fallbacks: {
    document: "/offline",
  },

  /**
   * Workbox runtime caching rules.
   * Be conservative with API caching (short TTL) and more aggressive with static assets.
   */
  runtimeCaching: [
    // External APIs: prefer fresh, fallback from cache quickly.
    {
      urlPattern: /^https:\/\/.*\/api\/.*$/i,
      handler: "NetworkFirst",
      options: {
        cacheName: "external-apis",
        networkTimeoutSeconds: 8,
        expiration: {
          maxEntries: 150,
          maxAgeSeconds: 3 * 60, // 3 minutes
        },
        cacheableResponse: {
          statuses: [0, 200, 201, 202, 204, 206, 301, 302, 404],
        },
        /**
         * Derive a cache key that varies by Authorization header and Content-Type
         * so authenticated or format-sensitive responses don't collide.
         */
        plugins: [
          {
            cacheKeyWillBeUsed: async ({ request }) => {
              const url = new URL(request.url);
              const auth = request.headers.get("Authorization");
              const contentType = request.headers.get("Content-Type");
              if (auth) url.searchParams.set("_auth_hash", btoa(auth).slice(-8));
              if (contentType) url.searchParams.set("_ct", contentType.split(";")[0]);
              return url.href;
            },
          },
        ],
      },
    },

    // Any cross-origin request that isn't matched above.
    {
      urlPattern: ({ url }) => url.origin !== globalThis.location.origin,
      handler: "NetworkFirst",
      options: {
        cacheName: "external-requests",
        networkTimeoutSeconds: 5,
        expiration: {
          maxEntries: 100,
          maxAgeSeconds: 2 * 60, // 2 minutes
        },
        cacheableResponse: {
          statuses: [0, 200, 201, 202, 204, 206],
        },
      },
    },

    // JSON responses (configs, small datasets): fast revalidation.
    {
      urlPattern: /\.(?:json)$/i,
      handler: "StaleWhileRevalidate",
      options: {
        cacheName: "json-responses",
        expiration: {
          maxEntries: 80,
          maxAgeSeconds: 15 * 60, // 15 minutes
        },
      },
    },

    // Static assets: cache-first with long TTLs.
    {
      urlPattern: /\.(?:png|jpg|jpeg|svg|gif|webp|ico|woff|woff2)$/i,
      handler: "CacheFirst",
      options: {
        cacheName: "static-assets",
        expiration: {
          maxEntries: 300,
          maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
        },
      },
    },

    // Common CDNs: cache-first with a week TTL.
    {
      urlPattern:
        /^https:\/\/(fonts\.googleapis\.com|fonts\.gstatic\.com|cdn\.jsdelivr\.net|unpkg\.com)/i,
      handler: "CacheFirst",
      options: {
        cacheName: "cdn-cache",
        expiration: {
          maxEntries: 50,
          maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
        },
      },
    },
  ],
});

/**
 * @type {import('next').NextConfig}
 *
 * Notes:
 * - Keep `optimizePackageImports` for lucide-react only (safe with pnpm).
 * - If you removed your `.babelrc`, Next will use SWC (recommended for monaco-editor).
 * - If you must keep Babel, ensure monaco packages are ignored there to avoid regex transforms.
 */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    optimizePackageImports: ["lucide-react"],
    /**
     * Optional: ensure these client-only libs never end up in the server bundle.
     * Not strictly necessary because your components son "use client", but harmless.
     */
  },
  outputFileTracingRoot: path.join(process.cwd()),
  // (Optional) If you serve from a subpath or behind a proxy, add basePath/assetPrefix here.
};

export default withPWAInit(nextConfig);
